# Generated by Django 2.0.7 on 2019-12-09 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_deck_slides', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['slide_deck', 'order'],
                'permissions': (('view_slide', 'View Slide'),),
            },
        ),
        migrations.CreateModel(
            name='SlideDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_decks', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Slide Deck',
                'verbose_name_plural': 'Slide Decks',
                'permissions': (('view_slidedeck', 'View Slide Deck'),),
            },
        ),
        migrations.CreateModel(
            name='SlideDeckTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('archived', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_deck_templates', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Slide Deck Template',
                'verbose_name_plural': 'Slide Deck Templates',
                'permissions': (('view_slidedecktemplate', 'View Slide Deck Template'),),
            },
        ),
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_deck_template_slides', to='contenttypes.ContentType')),
                ('slide_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_templates', to='presentations.SlideDeckTemplate')),
            ],
            options={
                'verbose_name': 'Slide Template',
                'verbose_name_plural': 'Slide Templates',
                'ordering': ['slide_deck', 'order'],
                'permissions': (('view_slidetemplate', 'View Slide Template'),),
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.SlideDeck'),
        ),
        migrations.AlterIndexTogether(
            name='slidetemplate',
            index_together={('slide_deck', 'order')},
        ),
        migrations.AlterIndexTogether(
            name='slide',
            index_together={('slide_deck', 'order')},
        ),
    ]
