# Generated by Django 2.0.7 on 2019-12-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20191213_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='presentations.SlideDeck'),
        ),
        migrations.AlterField(
            model_name='slidetemplate',
            name='slide_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_templates', to='presentations.SlideDeckTemplate'),
        ),
    ]
