# Generated by Django 2.0.7 on 2019-12-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_auto_20191217_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedecktemplate',
            name='use_dynamic_title',
            field=models.BooleanField(default=True),
        ),
    ]
