# Generated by Django 2.0.7 on 2020-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('presentations', '0004_slidedecktemplate_use_dynamic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidedecktemplate',
            name='is_master_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='slidedecktemplate',
            unique_together={('content_type', 'is_master_template')},
        ),
    ]
