# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_auto_20200114_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_deck', 'order'], 'permissions': (('view_slide__dep', 'View Slide Deprecated'),), 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='slidedeck',
            options={'permissions': (('view_slidedeck__dep', 'View Slide Deck Deprecated'),), 'verbose_name': 'Slide Deck', 'verbose_name_plural': 'Slide Decks'},
        ),
        migrations.AlterModelOptions(
            name='slidedecktemplate',
            options={'permissions': (('view_slidedecktemplate__dep', 'View Slide Deck Template Deprecated'),), 'verbose_name': 'Slide Deck Template', 'verbose_name_plural': 'Slide Deck Templates'},
        ),
        migrations.AlterModelOptions(
            name='slidetemplate',
            options={'ordering': ['slide_deck', 'order'], 'permissions': (('view_slidetemplate__dep', 'View Slide Template Deprecated'),), 'verbose_name': 'Slide Template', 'verbose_name_plural': 'Slide Templates'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='slidedeck',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='slidedecktemplate',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='slidedecktemplate',
            name='is_master_template',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='slidedecktemplate',
            name='use_dynamic_title',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='slidetemplate',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
