# Generated by Django 2.0.7 on 2018-12-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('view_organization', 'View Organization'),), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
