# Generated by Django 2.0.7 on 2019-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20190123_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
