# Generated by Django 2.0.7 on 2019-02-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
