# Generated by Django 2.0.7 on 2019-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20190221_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='dba_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
