# Generated by Django 2.0.7 on 2019-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20190726_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_required',
            field=models.BooleanField(default=False),
        ),
    ]
