# Generated by Django 2.0.7 on 2019-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_organization_report_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='report_required',
            field=models.BooleanField(default=True),
        ),
    ]
