# Generated by Django 2.0.7 on 2019-12-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20191217_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='monthly_report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponding_org_report_templates', to='presentations.SlideDeckTemplate'),
        ),
    ]
