# Generated by Django 2.0.7 on 2019-12-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20191217_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/logos/'),
        ),
    ]
