# Generated by Django 2.0.7 on 2020-01-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20200102_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatConvertsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200)),
                ('report_calls', models.BooleanField(default=True)),
                ('report_form_fills', models.BooleanField(default=True)),
                ('report_chats', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WhatConverts Account',
                'verbose_name_plural': 'WhatConverts Accounts',
                'permissions': (('view_whatconvertsaccount', 'View WhatConverts Account'),),
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='what_converts_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='what_converts_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wc_organizations', to='organizations.WhatConvertsAccount'),
        ),
    ]
