# Generated by Django 2.0.7 on 2020-01-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20200103_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatconvertsaccount',
            name='spt_account',
            field=models.BooleanField(default=False),
        ),
    ]
