# Generated by Django 2.0.7 on 2020-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_whatconvertsaccount_spt_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
