# Generated by Django 2.0.7 on 2020-09-14 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0021_organization_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
