# Generated by Django 2.0.7 on 2021-03-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_organization_account_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['dba_name'], 'permissions': (('view_organization', 'View Organization'),), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
    ]
