# Generated by Django 2.0.7 on 2019-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userorgrole_receive_reporting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorgrole',
            name='receive_approval_reminders',
            field=models.BooleanField(default=False),
        ),
    ]
