# Generated by Django 2.0.7 on 2019-12-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userorgrole_receive_approval_reminders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorgrole',
            options={'ordering': ('organization',), 'permissions': (('view_userorgrole', 'View User Org Role'),), 'verbose_name': 'User Organization Role', 'verbose_name_plural': 'User Organization Roles'},
        ),
    ]
