# Generated by Django 2.0.7 on 2020-01-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191204_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorgrole',
            name='receive_approval_reminders',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userorgrole',
            name='receive_reporting_email',
            field=models.NullBooleanField(default=False),
        ),
    ]
