# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_historicaluser_historicaluserorgrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferences',
            options={'permissions': (('view_preferences__dep', 'View Preferences Deprecated'),), 'verbose_name': 'User Preferences', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user__dep', 'View User Deprecated'),)},
        ),
        migrations.AlterModelOptions(
            name='userorgrole',
            options={'ordering': ('organization',), 'permissions': (('view_userorgrole__dep', 'View User Org Role Deprecated'),), 'verbose_name': 'User Organization Role', 'verbose_name_plural': 'User Organization Roles'},
        ),
    ]
