# Generated by Django 2.0.7 on 2019-07-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0065_auto_20190717_1418'),
        ('organizations', '0011_auto_20190726_2103'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('organization', 'month')},
        ),
    ]
