# Generated by Django 2.0.7 on 2019-08-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20190730_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_monthly_reports', to='organizations.Organization'),
        ),
    ]
