# Generated by Django 2.0.7 on 2020-01-02 19:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20191211_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonthlyreport',
            name='google_analytics_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='google_analytics_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
