# Generated by Django 2.0.7 on 2020-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20200103_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonthlyreport',
            name='detailed_organic_keywords_screenshot',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmonthlyreport',
            name='organic_keywords_screenshot',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmonthlyreport',
            name='referring_domains_screenshot',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmonthlyreport',
            name='referring_pages_screenshot',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='detailed_organic_keywords_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='report-screenshots/'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='organic_keywords_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='report-screenshots/'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='referring_domains_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='report-screenshots/'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='referring_pages_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='report-screenshots/'),
        ),
    ]
