# Generated by Django 2.0.7 on 2020-01-15 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20200109_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEmailEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Report Email Entry',
                'verbose_name_plural': 'Report Email Entries',
            },
        ),
    ]
