# Generated by Django 2.0.7 on 2020-01-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_reportemailentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemailentry',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportemailentry',
            name='link_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
