# Generated by Django 2.0.7 on 2020-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_reportemailentry_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemailentry',
            name='date_first_viewed',
            field=models.DateTimeField(null=True),
        ),
    ]
