# Generated by Django 2.0.7 on 2020-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_reportemailentry_date_first_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemailentry',
            name='did_unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
