# Generated by Django 2.0.7 on 2020-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_reportemailentry_did_unsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemailentry',
            name='date_unsubscribed',
            field=models.DateTimeField(null=True),
        ),
    ]
