# Generated by Django 2.0.7 on 2020-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_reportemailentry_date_unsubscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportemailentry',
            options={'ordering': ['date_sent'], 'verbose_name': 'Report Email Entry', 'verbose_name_plural': 'Report Email Entries'},
        ),
    ]
