# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_auto_20200218_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'permissions': (('view_monthlyreport__dep', 'View Monthly Report Deprecated'),), 'verbose_name': 'Monthly Report', 'verbose_name_plural': 'Monthly Reports'},
        ),
        migrations.AlterField(
            model_name='reportemailentry',
            name='did_unsubscribe',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reportemailentry',
            name='link_clicked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
