# Generated by Django 2.0.7 on 2019-04-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsitebuild',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebsitebuild',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='websitebuild',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websitebuild',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
