# Generated by Django 2.0.7 on 2019-07-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0005_auto_20190531_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsitebuild',
            name='brand_interview_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebsitebuild',
            name='sitemap_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websitebuild',
            name='brand_interview_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websitebuild',
            name='sitemap_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
