# Generated by Django 2.0.7 on 2019-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0006_auto_20190715_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebsitebuild',
            name='intake_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='websitebuild',
            name='intake_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
