# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_onboarding', '0008_auto_20190813_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitebuild',
            options={'permissions': (('view_websitebuild__dep', 'View Website Builds Deprecated'), ('initialize_websitebuild', 'Initialize Website Build')), 'verbose_name': 'Website Build', 'verbose_name_plural': 'Website Builds'},
        ),
        migrations.AlterField(
            model_name='historicalwebsitebuild',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='websitebuild',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
