# Generated by Django 2.0.7 on 2019-12-13 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicomponent',
            name='data_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
