# Generated by Django 2.0.7 on 2019-12-16 16:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_mapping', '0002_uicomponent_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicomponent',
            name='data_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
