# Generated by Django 2.0.7 on 2019-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0002_auto_20181213_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='is_writer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
