# Generated by Django 2.0.7 on 2019-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0003_auto_20190213_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
