# Generated by Django 2.0.7 on 2019-03-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0004_auto_20190326_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='create_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='send_invite',
            field=models.BooleanField(default=False),
        ),
    ]
