# Generated by Django 2.0.7 on 2020-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0007_auto_20190326_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='custominvitation',
            name='receive_approval_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custominvitation',
            name='receive_reporting_email',
            field=models.BooleanField(default=False),
        ),
    ]
