# Generated by Django 2.0.7 on 2020-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboarding', '0008_auto_20200115_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custominvitation',
            name='receive_approval_reminders',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custominvitation',
            name='receive_reporting_email',
            field=models.NullBooleanField(default=False),
        ),
    ]
