# Generated by Django 2.0.7 on 2019-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='channels',
            field=models.ManyToManyField(blank=True, to='content_management.ContentChannel'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='content_management.ContentKeywords'),
        ),
    ]
