# Generated by Django 2.0.7 on 2019-02-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0003_auto_20190131_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Tag',
                'verbose_name_plural': 'Content Tags',
                'permissions': (('view_contenttag', 'View Content Tag'),),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('volume', models.PositiveSmallIntegerField(default=1)),
                ('cost_per_click', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'permissions': (('view_keyword', 'View Keyword'),),
            },
        ),
        migrations.CreateModel(
            name='KeywordMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_value', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=100)),
                ('business_value', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_keyword_metas', to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_metas', to='content_management.Keyword')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_keyword_metas', to='organizations.Organization')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_keyword_metas', to='content_management.ContentTag')),
            ],
            options={
                'verbose_name': 'Keyword Meta',
                'verbose_name_plural': 'Keywords Metas',
                'permissions': (('view_keywordmeta', 'View Keyword Meta'),),
            },
        ),
        migrations.CreateModel(
            name='ParentKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_parent_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Keyword',
                'verbose_name_plural': 'Parent Keywords',
                'permissions': (('view_parentkeyword', 'View Parent Keyword'),),
            },
        ),
        migrations.CreateModel(
            name='UrlRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('ahrefs_rank', models.PositiveSmallIntegerField(default=1)),
                ('ahrefs_locations', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_rankings', to='content_management.Keyword')),
            ],
            options={
                'verbose_name': 'URL Ranking',
                'verbose_name_plural': 'URL Rankings',
                'permissions': (('view_urlranking', 'View URL Ranking'),),
            },
        ),
        migrations.AddField(
            model_name='writer',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
