# Generated by Django 2.0.7 on 2019-02-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_auto_20190205_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='parent_keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='content_management.ParentKeyword'),
        ),
    ]
