# Generated by Django 2.0.7 on 2019-02-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_keyword_parent_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Keyword Name'),
        ),
        migrations.AlterField(
            model_name='parentkeyword',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Parent Keyword Name'),
        ),
    ]
