# Generated by Django 2.0.7 on 2019-02-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_auto_20190205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='keywords',
            field=models.ManyToManyField(to='content_management.KeywordMeta'),
        ),
    ]
