# Generated by Django 2.0.7 on 2019-02-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0008_auto_20190205_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordmeta',
            name='tag',
        ),
        migrations.AddField(
            model_name='keywordmeta',
            name='tag',
            field=models.ManyToManyField(related_name='tag_keyword_metas', to='content_management.ContentTag'),
        ),
    ]
