# Generated by Django 2.0.7 on 2019-02-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_auto_20190206_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordmeta',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_keyword_metas', to='content_management.ContentTag'),
        ),
    ]
