# Generated by Django 2.0.7 on 2019-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0010_auto_20190206_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='keywordmeta',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentkeyword',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
