# Generated by Django 2.0.7 on 2019-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0012_auto_20190212_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='writer',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0.0, null=True),
        ),
    ]
