# Generated by Django 2.0.7 on 2019-02-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0013_auto_20190213_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcomments',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
