# Generated by Django 2.0.7 on 2019-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0015_auto_20190214_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keyword_meta_articles', to='content_management.KeywordMeta'),
        ),
    ]
