# Generated by Django 2.0.7 on 2019-02-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0016_auto_20190218_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentarticle',
            options={'permissions': (('view_contentarticle', 'View Content Article'), ('create_google_doc', 'Create Google Doc')), 'verbose_name': 'Content Article', 'verbose_name_plural': 'Content Articles'},
        ),
    ]
