# Generated by Django 2.0.7 on 2019-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0017_auto_20190218_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
