# Generated by Django 2.0.7 on 2019-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0018_auto_20190221_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=6),
        ),
    ]
