# Generated by Django 2.0.7 on 2019-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0020_auto_20190226_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='content_channels',
            field=models.ManyToManyField(to='content_management.ContentChannel'),
        ),
    ]
