# Generated by Django 2.0.7 on 2019-02-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0021_auto_20190226_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultWriter', to='content_management.Writer'),
        ),
    ]
