# Generated by Django 2.0.7 on 2019-02-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0022_auto_20190227_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, to='content_management.ContentChannel'),
        ),
    ]
