# Generated by Django 2.0.7 on 2019-02-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0024_auto_20190227_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='content_channels',
            field=models.ManyToManyField(blank=True, to='content_management.ContentChannel'),
        ),
    ]
