# Generated by Django 2.0.7 on 2019-02-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0025_auto_20190227_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='keywordmeta',
            name='business_value',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=100, null=True),
        ),
    ]
