# Generated by Django 2.0.7 on 2019-02-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0026_auto_20190228_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='cost_per_click',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='volume',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='keywordmeta',
            name='seo_value',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Low', max_length=100, null=True),
        ),
    ]
