# Generated by Django 2.0.7 on 2019-02-28 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0027_auto_20190228_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='parent_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='content_management.ParentKeyword'),
        ),
    ]
