# Generated by Django 2.0.7 on 2019-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0028_auto_20190228_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
