# Generated by Django 2.0.7 on 2019-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0029_auto_20190301_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='rate',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
