# Generated by Django 2.0.7 on 2019-03-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0030_auto_20190301_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultOrganizationTemplate', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultContentType', to='content_management.ContentType'),
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultEditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultApprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultWriter', to='content_management.Writer'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentClient', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentType', to='content_management.ContentType'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentEditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentApprover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentStatus', to='content_management.ContentStatus'),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentWriter', to='content_management.Writer'),
        ),
        migrations.AlterField(
            model_name='contentkeywords',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contenttag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='parent_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='content_management.ParentKeyword'),
        ),
        migrations.AlterField(
            model_name='keywordmeta',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keyword_metas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentkeyword',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parent_keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planningyearmonth',
            name='default_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_management.ContentStatus'),
        ),
    ]
