# Generated by Django 2.0.7 on 2019-03-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0031_auto_20190306_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordmeta',
            name='planning_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_year_month_keyword_metas', to='content_management.PlanningYearMonth'),
        ),
    ]
