# Generated by Django 2.0.7 on 2019-03-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0032_keywordmeta_planning_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordmeta',
            name='planning_month',
        ),
        migrations.AddField(
            model_name='keywordmeta',
            name='planning_months',
            field=models.ManyToManyField(blank=True, related_name='planning_year_month_keyword_metas', to='content_management.PlanningYearMonth'),
        ),
    ]
