# Generated by Django 2.0.7 on 2019-03-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0033_auto_20190306_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordmeta',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_keyword_metas', to='organizations.Organization'),
        ),
    ]
