# Generated by Django 2.0.7 on 2019-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0035_auto_20190307_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstatus',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
