# Generated by Django 2.0.7 on 2019-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0036_auto_20190307_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='channels',
            field=models.ManyToManyField(blank=True, to='content_management.ContentChannel'),
        ),
    ]
