# Generated by Django 2.0.7 on 2019-03-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0037_auto_20190307_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
