# Generated by Django 2.0.7 on 2019-03-11 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0038_contentstatus_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningyearmonth',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True),
        ),
        migrations.AlterField(
            model_name='planningyearmonth',
            name='year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
