# Generated by Django 2.0.7 on 2019-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0039_auto_20190311_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='duedate_draft',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contentstatus',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contentstatus',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='keywordmeta',
            name='planning_months',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='planning_year_month_keyword_metas', to='content_management.PlanningYearMonth'),
        ),
    ]
