# Generated by Django 2.0.7 on 2019-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0040_auto_20190312_2056'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='planningyearmonth',
            index=models.Index(fields=['year', 'month'], name='content_man_year_51c944_idx'),
        ),
    ]
