# Generated by Django 2.0.7 on 2019-03-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0041_auto_20190314_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentPoster', to=settings.AUTH_USER_MODEL),
        ),
    ]
