# Generated by Django 2.0.7 on 2019-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0043_contentarticle_writer_planned_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
