# Generated by Django 2.0.7 on 2019-03-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0044_contentarticle_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='volume',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
