# Generated by Django 2.0.7 on 2019-03-25 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0046_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
