# Generated by Django 2.0.7 on 2019-03-26 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0047_auto_20190325_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentLead', to=settings.AUTH_USER_MODEL),
        ),
    ]
