# Generated by Django 2.0.7 on 2019-03-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0049_articletemplate_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrequirements',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationrequirements',
            name='blog_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrequirements',
            name='blog_word_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationrequirements',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_requirements', to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationrequirements',
            name='press_release_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
