# Generated by Django 2.0.7 on 2019-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0051_auto_20190402_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='milestone',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), ('ASAP', 'ASAP')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='milestone',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), ('ASAP', 'ASAP')], max_length=25, null=True),
        ),
    ]
