# Generated by Django 2.0.7 on 2019-04-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0052_auto_20190403_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='planning_year_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentArticle', to='content_management.PlanningYearMonth'),
        ),
    ]
