# Generated by Django 2.0.7 on 2019-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0053_auto_20190403_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
