# Generated by Django 2.0.7 on 2019-04-18 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0010_auto_20190312_2058'),
        ('content_management', '0055_contentrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArticleTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('min_word_count', models.PositiveSmallIntegerField(null=True)),
                ('milestone', models.CharField(blank=True, choices=[(1, 1), (2, 2), ('ASAP', 'ASAP')], max_length=25, null=True)),
                ('price_production', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_distribution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('production_notes', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_update', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.Organization')),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.ContentType')),
                ('editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('final_approver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.Writer')),
            ],
            options={
                'verbose_name': 'historical Default Content Template',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContentArticle',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('google_doc', models.URLField(blank=True, max_length=500, null=True)),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_word_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('milestone', models.CharField(blank=True, choices=[(1, 1), (2, 2), ('ASAP', 'ASAP')], max_length=25, null=True)),
                ('duedate_draft', models.DateField(blank=True, db_index=True, null=True)),
                ('duedate_clientreview', models.DateField(blank=True, null=True)),
                ('duedate_golive', models.DateField(blank=True, null=True)),
                ('price_production', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_distribution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('url_1', models.URLField(blank=True, null=True)),
                ('anchor_1', models.CharField(blank=True, max_length=255, null=True)),
                ('url_2', models.URLField(blank=True, null=True)),
                ('anchor_2', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('writer_planned_duedate', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('last_update', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.Organization')),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.ContentType')),
                ('editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('final_approver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planning_year_month', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.PlanningYearMonth')),
                ('poster', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.ContentStatus')),
                ('writer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.Writer')),
            ],
            options={
                'verbose_name': 'historical Content Article',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
