# Generated by Django 2.0.7 on 2019-04-26 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0056_historicalarticletemplate_historicalcontentarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)])),
                ('start_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True)),
            ],
            options={
                'verbose_name': 'Content Project',
                'verbose_name_plural': 'Content Projects',
                'permissions': (('view_contentproject', 'View Content Project'),),
            },
        ),
        migrations.AddIndex(
            model_name='contentproject',
            index=models.Index(fields=['start_year', 'start_month'], name='content_man_start_y_a1dd35_idx'),
        ),
    ]
