# Generated by Django 2.0.7 on 2019-04-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0058_historicalcontentproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_articles', to='content_management.ContentProject'),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_management.ContentProject'),
        ),
    ]
