# Generated by Django 2.0.7 on 2019-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0062_auto_20190711_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contentproject',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentproject',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentproject',
            name='last_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
