# Generated by Django 2.0.7 on 2019-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0067_auto_20190812_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentarticle',
            options={'permissions': (('view_contentarticle', 'View Content Article'), ('create_google_doc', 'Create Google Doc'), ('edit_contentarticle', 'Edit Content Article'), ('write_contentarticle', 'Write Content Article'), ('approve_contentarticle', 'Approver Content Article')), 'verbose_name': 'Content Article', 'verbose_name_plural': 'Content Articles'},
        ),
        migrations.AddField(
            model_name='planningyearmonth',
            name='editor_due_date_offset',
            field=models.PositiveSmallIntegerField(blank=True, default=14, null=True),
        ),
    ]
