# Generated by Django 2.0.7 on 2020-01-02 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0073_auto_20191205_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AlterField(
            model_name='contentrequirement',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
