# Generated by Django 2.0.7 on 2020-02-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0074_auto_20200102_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2),
        ),
    ]
