# Generated by Django 2.0.7 on 2020-03-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0076_auto_20200306_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentArticleHistorySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateTimeField()),
                ('incomplete_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('complete_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('late_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_article_history_set', to='content_management.ContentStatus')),
            ],
            options={
                'verbose_name': 'Content Article History Set',
                'verbose_name_plural': 'Content Article History Sets',
            },
        ),
    ]
