# Generated by Django 2.0.7 on 2020-03-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0080_auto_20200324_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentarticlehistoryset',
            options={'ordering': ['-as_of_date'], 'verbose_name': 'Content Article History Set', 'verbose_name_plural': 'Content Article History Sets'},
        ),
    ]
