# Generated by Django 2.0.7 on 2020-03-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0081_auto_20200324_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='duedate_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='duedate_scheduled',
            field=models.DateField(blank=True, null=True),
        ),
    ]
