# Generated by Django 2.0.7 on 2020-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0082_auto_20200327_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstatus',
            name='due_date_day_offset',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
