# Generated by Django 2.0.7 on 2020-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0083_contentstatus_due_date_day_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='duedate_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentarticle',
            name='duedate_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
