# Generated by Django 2.0.7 on 2021-01-15 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0086_auto_20200914_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='duedate_edit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentarticle',
            name='duedate_reedit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentarticle',
            name='duedate_rewrite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='duedate_edit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='duedate_reedit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='duedate_rewrite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
        ),
        migrations.AlterField(
            model_name='contentrequirement',
            name='year',
            field=models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
