# Generated by Django 2.0.7 on 2021-01-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0087_auto_20210115_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_articles', to='content_management.ContentProject'),
        ),
    ]
