# Generated by Django 2.0.7 on 2021-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0089_auto_20210122_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='duedate_finalreview',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='duedate_finalreview',
            field=models.DateField(blank=True, null=True),
        ),
    ]
