# Generated by Django 2.0.7 on 2021-01-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0090_auto_20210122_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentarticle',
            name='duedate_schedulepost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentarticle',
            name='duedate_schedulepost',
            field=models.DateField(blank=True, null=True),
        ),
    ]
