# Generated by Django 2.0.7 on 2021-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0092_auto_20210126_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='focus_keyword_plaintext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='focus_keyword_plaintext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2),
        ),
    ]
