# Generated by Django 2.0.7 on 2021-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0093_auto_20210204_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletemplate',
            options={'ordering': ['client__dba_name', 'title'], 'permissions': (('view_articletemplate', 'View Article Template'),), 'verbose_name': 'Default Content Template', 'verbose_name_plural': 'Default Content Templates'},
        ),
        migrations.AlterModelOptions(
            name='contentarticle',
            options={'ordering': ['status__order', 'planning_year_month__year', 'planning_year_month__month'], 'permissions': (('view_contentarticle', 'View Content Article'), ('create_google_doc', 'Create Google Doc'), ('edit_contentarticle', 'Edit Content Article'), ('write_contentarticle', 'Write Content Article'), ('approve_contentarticle', 'Approver Content Article')), 'verbose_name': 'Content Article', 'verbose_name_plural': 'Content Articles'},
        ),
        migrations.AlterModelOptions(
            name='planningyearmonth',
            options={'ordering': ['-year', '-month'], 'permissions': (('view_planningyearmonth', 'View Planning Year Month'),), 'verbose_name': 'Planning Month', 'verbose_name_plural': 'Planning Months'},
        ),
        migrations.AlterField(
            model_name='contentrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3),
        ),
    ]
