# Generated by Django 2.0.7 on 2021-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0094_auto_20210330_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstatus',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='milestone',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='production_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='milestone',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticletemplate',
            name='milestone',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticletemplate',
            name='production_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentarticle',
            name='milestone',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2')], max_length=25, null=True),
        ),
    ]
