# Generated by Django 2.0.7 on 2021-04-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0095_auto_20210331_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='milestone',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='milestone',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contentrequirement',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4),
        ),
        migrations.AlterField(
            model_name='historicalarticletemplate',
            name='milestone',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontentarticle',
            name='milestone',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=25, null=True),
        ),
    ]
