# Generated by Django 2.0.7 on 2021-04-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0096_auto_20210405_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='admin_draft_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='admin_draft_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
