# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0097_auto_20210406_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletemplate',
            options={'ordering': ['client__dba_name', 'title'], 'permissions': (('view_articletemplate__dep', 'View Article Template Deprecated'),), 'verbose_name': 'Default Content Template', 'verbose_name_plural': 'Default Content Templates'},
        ),
        migrations.AlterModelOptions(
            name='contentarticle',
            options={'ordering': ['status__order', 'planning_year_month__year', 'planning_year_month__month'], 'permissions': (('view_contentarticle__dep', 'View Content Article Deprecated'), ('create_google_doc', 'Create Google Doc'), ('edit_contentarticle', 'Edit Content Article'), ('write_contentarticle', 'Write Content Article'), ('approve_contentarticle', 'Approver Content Article')), 'verbose_name': 'Content Article', 'verbose_name_plural': 'Content Articles'},
        ),
        migrations.AlterModelOptions(
            name='contentchannel',
            options={'permissions': (('view_contentchannel__dep', 'View Content Channel Deprecated'),), 'verbose_name': 'Content Channel', 'verbose_name_plural': 'Content Channel'},
        ),
        migrations.AlterModelOptions(
            name='contentcomments',
            options={'permissions': (('view_contentcomments__dep', 'View Content Comments Deprecated'),), 'verbose_name': 'Content Comment', 'verbose_name_plural': 'Content Comments'},
        ),
        migrations.AlterModelOptions(
            name='contentkeywords',
            options={'permissions': (('view_contentkeywords__dep', 'View Content Keywords Deprecated'),), 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='contentproject',
            options={'permissions': (('view_contentproject__dep', 'View Content Project Deprecated'),), 'verbose_name': 'Content Project', 'verbose_name_plural': 'Content Projects'},
        ),
        migrations.AlterModelOptions(
            name='contentrequirement',
            options={'permissions': (('view_contentrequirement__dep', 'View Content Requirement Deprecated'),), 'verbose_name': 'Content Requirement', 'verbose_name_plural': 'Content Requirements'},
        ),
        migrations.AlterModelOptions(
            name='contentstatus',
            options={'permissions': (('view_contentstatus__dep', 'View Content Status Deprecated'),), 'verbose_name': 'Content Status', 'verbose_name_plural': 'Content Status'},
        ),
        migrations.AlterModelOptions(
            name='contenttag',
            options={'permissions': (('view_contenttag__dep', 'View Content Tag Deprecated'),), 'verbose_name': 'Content Tag', 'verbose_name_plural': 'Content Tags'},
        ),
        migrations.AlterModelOptions(
            name='contenttype',
            options={'permissions': (('view_contenttype__dep', 'View Content Type Deprecated'),), 'verbose_name': 'Content Type', 'verbose_name_plural': 'Content Types'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('view_feedback__dep', 'View Feedback Deprecated'),), 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'permissions': (('view_keyword__dep', 'View Keyword Deprecated'),), 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='keywordmeta',
            options={'permissions': (('view_keywordmeta__dep', 'View Keyword Meta Deprecated'),), 'verbose_name': 'Keyword Meta', 'verbose_name_plural': 'Keywords Metas'},
        ),
        migrations.AlterModelOptions(
            name='organizationeditorialrequirement',
            options={'permissions': (('view_organizationeditorialrequirement__dep', 'Organization Editorial Requirement Deprecated'),), 'verbose_name': 'Organization Editorial Requirement', 'verbose_name_plural': 'Organization Editorial Requirements'},
        ),
        migrations.AlterModelOptions(
            name='organizationrequirements',
            options={'permissions': (('view_organizationrequirements__dep', 'View Organization Requirements Deprecated'),), 'verbose_name': 'Organization Requirement', 'verbose_name_plural': 'Organization Requirements'},
        ),
        migrations.AlterModelOptions(
            name='parentkeyword',
            options={'permissions': (('view_parentkeyword__dep', 'View Parent Keyword Deprecated'),), 'verbose_name': 'Parent Keyword', 'verbose_name_plural': 'Parent Keywords'},
        ),
        migrations.AlterModelOptions(
            name='planningtemplateorder',
            options={'permissions': (('view_planningtemplateorder__dep', 'View Planning Template Order Deprecated'),), 'verbose_name': 'Planning Template', 'verbose_name_plural': 'Planning Templates'},
        ),
        migrations.AlterModelOptions(
            name='planningyearmonth',
            options={'ordering': ['-year', '-month'], 'permissions': (('view_planningyearmonth__dep', 'View Planning Year Month Deprecated'),), 'verbose_name': 'Planning Month', 'verbose_name_plural': 'Planning Months'},
        ),
        migrations.AlterModelOptions(
            name='urlranking',
            options={'permissions': (('view_urlranking__dep', 'View URL Ranking Deprecated'),), 'verbose_name': 'URL Ranking', 'verbose_name_plural': 'URL Rankings'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'permissions': (('view_writer__dep', 'View Writer Deprecated'),), 'verbose_name': 'Writer', 'verbose_name_plural': 'Writers'},
        ),
        migrations.AlterField(
            model_name='articletemplate',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contentarticle',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contentproject',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contentstatus',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalarticletemplate',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalcontentarticle',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalcontentproject',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='keywordmeta',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='parentkeyword',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
