# Generated by Django 2.2 on 2021-04-22 18:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0098_auto_20210422_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningtemplateorder',
            name='article_order_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='planningyearmonth',
            name='article_order_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
