# Generated by Django 2.2 on 2021-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0100_auto_20210512_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentarticle',
            name='duedate_qapost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentarticle',
            name='duedate_qapost',
            field=models.DateField(blank=True, null=True),
        ),
    ]
