# Generated by Django 2.0.7 on 2019-04-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'permissions': (('view_userfeedback', 'View User Feedback'),), 'verbose_name': 'User Feedback'},
        ),
    ]
