# Generated by Django 2.0.7 on 2020-03-09 16:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0021_organization_contract_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leads_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('organic_traffic_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_health', to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'Account Health',
                'verbose_name_plural': 'Account Health',
                'permissions': (('view_accounthealth__dep', 'View Account Health Deprecated'),),
            },
        ),
    ]
