# Generated by Django 2.0.7 on 2020-03-16 18:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthealth',
            name='desktop_page_speed_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounthealth',
            name='mobile_page_speed_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
