# Generated by Django 2.0.7 on 2019-04-22 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'permissions': (('view_checklist', 'View Checklist'),), 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AddField(
            model_name='checklist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalchecklist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalchecklistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
