# Generated by Django 2.0.7 on 2019-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20190422_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalchecklistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalchecklistitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalchecklisttemplateitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalchecklisttemplateitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
