# Generated by Django 2.0.7 on 2019-04-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_auto_20190422_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitemattachment',
            options={'permissions': (('view_checklistitemattachment', 'View Checklist Item Attachment'),), 'verbose_name': 'Checklist Item Attachment', 'verbose_name_plural': 'Checklist Item Attachments'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitemattachment',
            options={'permissions': (('view_checklisttemplateitemattachment', 'View Checklist Template Item Attachment'),), 'verbose_name': 'Checklist Template Item Attachment', 'verbose_name_plural': 'Checklist Template Item Attachments'},
        ),
        migrations.AlterField(
            model_name='checklisttemplateitemattachment',
            name='checklist_template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_template_item_attachments', to='checklists.ChecklistTemplateItem'),
        ),
    ]
