# Generated by Django 2.0.7 on 2019-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_auto_20190422_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitemattachment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitemattachment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
