# Generated by Django 2.0.7 on 2019-04-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_auto_20190422_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalchecklisttemplateitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
