# Generated by Django 2.0.7 on 2019-05-10 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_auto_20190509_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalchecklist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalchecklisttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalchecklisttemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
