# Generated by Django 2.0.7 on 2019-05-16 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0011_auto_20190510_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='historicalchecklisttemplateitem',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
