# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0013_auto_20190516_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'permissions': (('view_checklist__dep', 'View Checklist Deprecated'),), 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['checklist', 'order'], 'permissions': (('view_checklistitem__dep', 'View Checklist Item Deprecated'),), 'verbose_name': 'Checklist Item', 'verbose_name_plural': 'Checklist Items'},
        ),
        migrations.AlterModelOptions(
            name='checklistitemattachment',
            options={'permissions': (('view_checklistitemattachment__dep', 'View Checklist Item Attachment Deprecated'),), 'verbose_name': 'Checklist Item Attachment', 'verbose_name_plural': 'Checklist Item Attachments'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'permissions': (('view_checklisttemplate__dep', 'View Checklist Template Deprecated'),), 'verbose_name': 'Checklist Template', 'verbose_name_plural': 'Checklist Templates'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitem',
            options={'ordering': ['checklist', 'order'], 'permissions': (('view_checklisttemplateitem__dep', 'View Checklist Template Item Deprecated'),), 'verbose_name': 'Checklist Template Item', 'verbose_name_plural': 'Checklist Template Items'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitemattachment',
            options={'permissions': (('view_checklisttemplateitemattachment__dep', 'View Checklist Template Item Attachment Deprecated'),), 'verbose_name': 'Checklist Template Item Attachment', 'verbose_name_plural': 'Checklist Template Item Attachments'},
        ),
        migrations.AlterModelOptions(
            name='masterchecklisttemplate',
            options={'permissions': (('view_masterchecklisttemplate__dep', 'View Master Checklist Templates Deprecated'),), 'verbose_name': 'Master Checklist Templates', 'verbose_name_plural': 'Master Checklist Templates'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalchecklist',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalchecklistitem',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalchecklisttemplate',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
