# Generated by Django 2.0.7 on 2019-12-16 16:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Component Name')),
                ('attribute_fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'UI Component',
                'verbose_name_plural': 'UI Components',
                'permissions': (('view_uicomponent', 'View UI Component'),),
            },
        ),
    ]
