# Generated by Django 2.0.7 on 2019-12-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uicomponent',
            name='verbose_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Component Verbose Name'),
        ),
    ]
