# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_mapping', '0002_uicomponent_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uicomponent',
            options={'permissions': (('view_uicomponent__dep', 'View UI Component Deprecated'),), 'verbose_name': 'UI Component', 'verbose_name_plural': 'UI Components'},
        ),
        migrations.AlterField(
            model_name='uicomponent',
            name='is_allowed',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
