# Generated by Django 2.0.7 on 2019-06-03 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_onboarding', '0005_auto_20190531_1832'),
        ('organizations', '0010_auto_20190312_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=255)),
                ('zip_file', models.FileField(upload_to='uploads/genesis-child-themes/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Child Theme',
                'verbose_name_plural': 'Child Themes',
                'permissions': (('view_childtheme', 'View Child Themes'),),
            },
        ),
        migrations.CreateModel(
            name='HistoricalWebApp',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('alias', models.CharField(default='New Web Application', max_length=255)),
                ('staging_url', models.URLField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_build', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='client_onboarding.WebsiteBuild')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'historical Web Application',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='New Web Application', max_length=255)),
                ('staging_url', models.URLField(blank=True, null=True)),
                ('production_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('new_build', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_application', to='client_onboarding.WebsiteBuild')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_applications', to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'Web Application',
                'verbose_name_plural': 'Web Applications',
                'permissions': (('view_webapplication', 'View Web Application'),),
            },
        ),
    ]
