# Generated by Django 2.0.7 on 2019-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0002_auto_20190604_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebapp',
            name='staging_db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebapp',
            name='staging_wordpress_db_passwrd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalwebapp',
            name='staging_wordpress_db_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webapp',
            name='staging_db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webapp',
            name='staging_wordpress_db_passwrd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webapp',
            name='staging_wordpress_db_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
