# Generated by Django 2.0.7 on 2019-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0003_auto_20190604_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalwebapp',
            old_name='staging_wordpress_db_passwrd',
            new_name='staging_wordpress_db_password',
        ),
        migrations.RenameField(
            model_name='webapp',
            old_name='staging_wordpress_db_passwrd',
            new_name='staging_wordpress_db_password',
        ),
        migrations.AddField(
            model_name='historicalwebapp',
            name='initialization_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webapp',
            name='initialization_complete',
            field=models.BooleanField(default=False),
        ),
    ]
