# Generated by Django 2.0.7 on 2019-06-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0004_auto_20190604_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webapp',
            options={'permissions': (('view_webapp', 'View Web Application'),), 'verbose_name': 'Web Application', 'verbose_name_plural': 'Web Applications'},
        ),
    ]
