# Generated by Django 2.0.7 on 2019-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0006_auto_20190605_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebapp',
            name='site_name',
            field=models.CharField(default='newwebapp.com', max_length=255),
        ),
        migrations.AddField(
            model_name='webapp',
            name='site_name',
            field=models.CharField(default='newwebapp.com', max_length=255),
        ),
    ]
