# Generated by Django 2.0.7 on 2019-06-07 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0007_auto_20190605_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebapp',
            name='nginx_port',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(80)]),
        ),
        migrations.AddField(
            model_name='webapp',
            name='nginx_port',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(80)]),
        ),
    ]
