# Generated by Django 2.0.7 on 2019-06-07 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0008_auto_20190607_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebapp',
            name='nginx_port',
            field=models.IntegerField(blank=True, default=80, null=True, validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='nginx_port',
            field=models.IntegerField(blank=True, default=80, null=True, validators=[django.core.validators.MaxValueValidator(160), django.core.validators.MinValueValidator(80)]),
        ),
    ]
