# Generated by Django 2.0.7 on 2019-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0010_auto_20190607_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwebapp',
            name='scheduled_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webapp',
            name='scheduled_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
