# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_deployments', '0011_auto_20190711_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childtheme',
            options={'permissions': (('view_childtheme__dep', 'View Child Themes Deprecated'),), 'verbose_name': 'Child Theme', 'verbose_name_plural': 'Child Themes'},
        ),
        migrations.AlterModelOptions(
            name='webapp',
            options={'permissions': (('view_webapp__dep', 'View Web Application Deprecated'), ('execute_command', 'Execute Remote Command')), 'verbose_name': 'Web Application', 'verbose_name_plural': 'Web Applications'},
        ),
        migrations.AlterField(
            model_name='childtheme',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalwebapp',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='historicalwebapp',
            name='initialization_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalwebapp',
            name='scheduled_for_deletion',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='initialization_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='scheduled_for_deletion',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
