# Generated by Django 2.0.7 on 2018-12-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': (('view_notification', 'View Notification'),), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
