# Generated by Django 2.0.7 on 2021-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20181206_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('live_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'permissions': (('view_systemnotification', 'Can view system notification'),),
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': (('view_notification', 'Cay  Andn view notification'),), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
