# Generated by Django 2.2 on 2021-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20210330_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': (('view_notification__dep', 'Cay  Andn view notification Deprecated'),), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='systemnotification',
            options={'permissions': (('view_systemnotification__dep', 'Can view system notification Deprecated'),), 'verbose_name': 'System Notification', 'verbose_name_plural': 'System Notifications'},
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
